### ISSUE TITLE
Regenerating prices file fails

### ISSUE THREAD

**Issue by JaggeV** [eyeonus/EDDBlink#2]
Ok, after nearly 24h of waiting, the plugin fails in the final moments:
NOTE: Downloading file: 'eddb/listings.csv'.
NOTE: Requesting http://elite.ripz.org/files/listings.csv
NOTE: Downloaded 149.0MB of uncompressed data   8.6MB/s
NOTE: Processing market data: Start time = 2018-05-03 14:49:10.842362
NOTE: Finished processing market data. End time = 2018-05-03 14:54:20.656794
NOTE: /home/jagge/trade2/data/RareItem.csv re-exported.
NOTE: Regenerating .prices file.
Traceback (most recent call last):
  File "trade.py", line 104, in <module>
    main(sys.argv)
  File "trade.py", line 77, in main
    results = cmdenv.run(tdb)
  File "trade2/commands/commandenv.py", line 81, in run
    return self._cmd.run(results, self, tdb)
  File "trade2/commands/import_cmd.py", line 124, in run
    if not plugin.run():
  File "trade2/plugins/eddblink_plug.py", line 751, in run
    cache.regeneratePricesFile(tdb, tdenv)
  File "trade2/cache.py", line 1159, in regeneratePricesFile
    debug=tdenv.debug)
  File "/home/jagge/trade2/prices.py", line 62, in dumpPrices
    longestName = max(items.values(), key=lambda ent: len(ent[0]))
ValueError: max() arg is an empty sequence

I have not analyzed the problem yet, but will study the error more when I have the time.

**Comment by Tromador** [comment]
Yeah, I got the exact same. 

This was whilst running -O clean. Did take a while to process upgrade vendors which I suspect is why @JaggeV had watched it all day. 

Tried running with -www, but that didn't give any additional diagnostic.

**Comment by eyeonus** [comment]
The Items database isn't getting filled, that's where the problem is coming from. I think I borked something.

**Comment by eyeonus** [comment]
Oh wow, am I an idiot.
