### ISSUE TITLE
Suggestion: INSERT OR REPLACE?

### ISSUE THREAD

**Issue by aadler** [eyeonus/EDDBlink#4]
I know close to nothing about SQL, but sqlite3 does have a version of `UPSERT` called `INSERT OR REPLACE` (see [this](https://stackoverflow.com/questions/22777793/insert-or-replace-in-sqlite3-where-column?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa) and [this](https://stackoverflow.com/questions/418898/sqlite-upsert-not-insert-or-replace?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa) SO questions. That may be faster than the IF...UPDATE...ELSE...INSERT that you use now. Something to consider, if I understood it properly :)

Thanks!

**Comment by eyeonus** [comment]
Nope. It's slower, because it's not equivalent to insert if not exist, update if does, it's equivalent to insert if doesn't exist, delete and insert if does.

Deleting from the database is literally the SLOWEST operation.
